name: flutter_ecatalog
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  camera: ^0.10.5+2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  http: ^1.0.0
  image_picker: ^0.8.8
  json_annotation: ^4.8.1
  shared_preferences: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
